### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by bismasaeed00** [bismasaeed00/BSLoader#1]
![simulator screen shot - iphone x - 2017-10-09 at 10 50 41](https://user-images.githubusercontent.com/16186934/31326422-81b088ba-ace0-11e7-9ce6-0dde58d99b6e.png)

**Comment by rajdhakate** [comment]
maybe a gif to show it in action

**Comment by bismasaeed00** [comment]
yes but I am hopping to customise it's colour choices. That's why creating circles and fill them with colours.
